<?php

/**
 * The class holding all the logic for the 'Microsoft Entra ID' settings page used to configure the plugin.
 *
 * Partially generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
class AADSSO_Settings_Page {

	/**
	 * The stored settings (with defaults, if the setting isn't stored).
	 */
	private $settings;

	/**
	 * Setting keys whose value currently comes from an environment variable.
	 */
	private $settings_from_env = array();

	/**
	 * The option page's hook_suffix returned from add_options_page
	 */
	private $options_page_id;

	public function __construct() {

		// Ensure jQuery is loaded.
		add_action( 'admin_enqueue_scripts', array( $this, 'maybe_include_jquery' ) );

		// Add the settings page.
		if ( is_multisite() ) {
			add_action( 'network_admin_menu', array( $this, 'add_options_page' ) );
		} else {
			add_action( 'admin_menu', array( $this, 'add_options_page' ) );
		}

		// Register the settings.
		add_action( 'admin_init', array( $this, 'register_settings' ) );

		// In Multisite, handle saving via a custom Network Admin handler.
		if ( is_multisite() ) {
			add_action( 'admin_post_aadsso_save_settings', array( $this, 'handle_network_settings_save' ) );
		}

		// Reset settings if requested to.
		add_action( 'admin_init', array( $this, 'maybe_reset_settings' ) );

		// Migrate settings if requested to.
		add_action( 'admin_init', array( $this, 'maybe_migrate_settings' ) );

		if ( is_multisite() ) {
			// Ensure these also run in Network Admin.
			add_action( 'network_admin_edit_aadsso_settings', array( $this, 'register_settings' ) );
			add_action( 'network_admin_edit_aadsso_settings', array( $this, 'maybe_reset_settings' ) );
			add_action( 'network_admin_edit_aadsso_settings', array( $this, 'maybe_migrate_settings' ) );
		}

		// If settings were reset, show confirmation.
		add_action( 'all_admin_notices', array( $this, 'notify_if_reset_successful' ) );

		// If settings were migrated, show confirmation
		add_action( 'all_admin_notices', array( $this, 'notify_json_migrate_status' ) );

		// Remove query arguments from the REQUEST_URI (leaves $_GET untouched).  Resolves issue #58
		$_SERVER['REQUEST_URI'] = remove_query_arg( 'aadsso_reset', $_SERVER['REQUEST_URI'] );
		$_SERVER['REQUEST_URI'] = remove_query_arg( 'aadsso_migrate_from_json_status', $_SERVER['REQUEST_URI'] );

		// Load raw DB value directly via $wpdb to bypass any stale Redis/object-cache
		// that was causing get_site_option() to return false even when data existed.
		if ( is_multisite() ) {
			global $wpdb;
			$network_id      = get_current_network_id();
			$raw_meta_value  = $wpdb->get_var( $wpdb->prepare(
				"SELECT meta_value FROM {$wpdb->sitemeta} WHERE site_id = %d AND meta_key = 'aadsso_settings' ORDER BY meta_id DESC LIMIT 1",
				$network_id
			) );
			$stored_settings = $raw_meta_value ? maybe_unserialize( $raw_meta_value ) : false;
		} else {
			$stored_settings = get_option( 'aadsso_settings' );
		}
		$stored_settings = is_array( $stored_settings ) ? $stored_settings : array();

		// Start from the raw DB values.
		$this->settings = $stored_settings;

		// Apply environment variables for any key not explicitly saved in the DB
		// (or saved as an empty string). Env vars take precedence over WP defaults.
		foreach ( AADSSO_Settings::get_settings_from_env() as $key => $value ) {
			$in_db    = array_key_exists( $key, $stored_settings );
			$db_empty = $in_db && $stored_settings[ $key ] === '';

			if ( ! $in_db || $db_empty ) {
				$this->settings[ $key ] = $value;
				$this->settings_from_env[] = $key;
			}
		}

		// Apply WordPress defaults for anything still missing.
		$default_settings = AADSSO_Settings::get_defaults();
		foreach ( $default_settings as $key => $default_value ) {
			if ( ! isset( $this->settings[ $key ] ) ) {
				$this->settings[ $key ] = $default_value;
			}
		}
	}

	/**
	 * Clears settings if $_GET['aadsso_nonce'] is set and if the nonce is valid.
	 */
	public function maybe_reset_settings()
	{
		$should_reset_settings = isset( $_GET['aadsso_nonce'] )
		                          && wp_verify_nonce( $_GET['aadsso_nonce'], 'aadsso_reset_settings' );
		if ( $should_reset_settings ) {
			if ( is_multisite() ) {
				delete_site_option( 'aadsso_settings' );
				wp_redirect( network_admin_url( 'settings.php?page=aadsso_settings&aadsso_reset=success' ) );
			} else {
				delete_option( 'aadsso_settings' );
				wp_redirect( admin_url( 'options-general.php?page=aadsso_settings&aadsso_reset=success' ) );
			}
		}
	}

	/**
	 * Migrates old settings (Settings.json) to the database and attempts to delete the old settings file.
	 */
	public function maybe_migrate_settings() {
		/**
		 * Settings should only be migrated if
		 * - The request came from a nonced link
		 * - The nonce action is 'aadsso_migrate_settings'
		 * - There is a legacy settings path defined
		 * - There is a file at that legacy settings path
		 */
		$should_migrate_settings = isset( $_GET['aadsso_nonce'] )
			&& wp_verify_nonce( $_GET['aadsso_nonce'], 'aadsso_migrate_from_json' )
			&& defined( 'AADSSO_SETTINGS_PATH' )
			&& file_exists( AADSSO_SETTINGS_PATH );

		if ( $should_migrate_settings ) {

			$legacy_settings = json_decode( file_get_contents( AADSSO_SETTINGS_PATH ), true );

			if ( null === $legacy_settings ) {
				if ( is_multisite() ) {
					wp_redirect( network_admin_url( 'settings.php?page=aadsso_settings&aadsso_migrate_from_json_status=invalid_json') );
				} else {
					wp_redirect( admin_url( 'options-general.php?page=aadsso_settings&aadsso_migrate_from_json_status=invalid_json') );
				}
			}

			// If aad_group_to_wp_role_map is set in the legacy settings, build the inverted role_map array,
			// which is what is ultimately saved in the database.
			if ( isset( $legacy_settings['aad_group_to_wp_role_map'] ) ) {
				$legacy_settings['role_map'] = array();
				foreach ($aad_group_to_wp_role_map as $group_id => $role_slug ) {
					if ( ! isset( $legacy_settings['role_map'][$role_slug] ) ) {
						$legacy_settings['role_map'][$role_slug] = $group_id;
					} else {
						$legacy_settings['role_map'][$role_slug] .= ',' . $group_id;
					}
				}
			}

			$sanitized_settings = $this->sanitize_settings( $legacy_settings );

			if ( is_multisite() ) {
				update_site_option( 'aadsso_settings', $sanitized_settings );
			} else {
				update_option( 'aadsso_settings', $sanitized_settings );
			}

			if ( is_writable( AADSSO_SETTINGS_PATH ) && is_writable( dirname( AADSSO_SETTINGS_PATH ) ) && unlink( AADSSO_SETTINGS_PATH ) ) {
				if ( is_multisite() ) {
					wp_redirect( network_admin_url( 'settings.php?page=aadsso_settings&aadsso_migrate_from_json_status=success' ) );
				} else {
					wp_redirect( admin_url( 'options-general.php?page=aadsso_settings&aadsso_migrate_from_json_status=success' ) );
				}
			} else {
				if ( is_multisite() ) {
					wp_redirect( network_admin_url( 'settings.php?page=aadsso_settings&aadsso_migrate_from_json_status=manual' ) );
				} else {
					wp_redirect( admin_url( 'options-general.php?page=aadsso_settings&aadsso_migrate_from_json_status=manual' ) );
				}
			}
		}
	}

	/**
	 * Shows messages about the state of the migration operation
	 */
	public function notify_json_migrate_status() {
		if( isset( $_GET['aadsso_migrate_from_json_status'] ) ) {
			if( 'success' === $_GET['aadsso_migrate_from_json_status'] ) {
				echo '<div id="message" class="notice notice-success"><p>'
					. __( 'Legacy settings have been migrated and the old configuration file has been deleted.', 'aad-sso-wordpress' )
					. __('To finish migration, unset <code>AADSSO_SETTINGS_PATH</code> from <code>wp-config.php</code>. ', 'aad-sso-wordpress')
					.'</p></div>';
			} elseif ( 'manual' === $_GET['aadsso_migrate_from_json_status'] ) {
				echo '<div id="message" class="notice notice-warning"><p>'
					. esc_html__( 'Legacy settings have been migrated successfully. ', 'aad-sso-wordpress' )
					. sprintf( __('To finish migration, delete the file at the path <code>%s</code>. ', 'aad-sso-wordpress'), AADSSO_SETTINGS_PATH )
					. sprintf( __('Then, unset <code>AADSSO_SETTINGS_PATH</code> from <code>wp-config.php</code>. ', 'aad-sso-wordpress') )
					.'</p></div>';
			} elseif( 'invalid_json' === $_GET['aadsso_migrate_from_json_status'] ) {
				echo '<div id="message" class="notice notice-error"><p>'
					. sprintf( __('Legacy settings could not be migrated from <code>%s</code>. ', 'aad-sso-wordpress'), AADSSO_SETTINGS_PATH )
					. esc_html( 'File could not be parsed as JSON. ', 'aad-sso-wordpress' )
					. esc_html( 'Delete the file, or check its syntax.', 'aad-sso-wordpress' )
					.'</p></div>';
			}
		}
	}

	/**
	 * Notifies user if settings reset was successful.
	 */
	public function notify_if_reset_successful()
	{
		if ( isset( $_GET['aadsso_reset'] ) && 'success' === $_GET['aadsso_reset'] ) {
			echo '<div id="message" class="notice notice-warning"><p>'
				. __( 'Single Sign-on with Microsoft Entra ID settings have been reset to default.',
					'aad-sso-wordpress' )
				.'</p></div>';
		}
	}

	/**
	 * Adds the 'Microsoft Entra ID' options page.
	 */
	public function add_options_page() {
		if ( is_multisite() ) {
			$this->options_page_id = add_submenu_page(
				'settings.php',
				__( 'Microsoft Entra ID Settings', 'aad-sso-wordpress' ),
				'Microsoft Entra ID',
				'manage_network_options',
				'aadsso_settings',
				array( $this, 'render_admin_page' )
			);
		} else {
			$this->options_page_id = add_options_page(
				__( 'Microsoft Entra ID Settings', 'aad-sso-wordpress' ),
				'Microsoft Entra ID',
				'manage_options',
				'aadsso_settings',
				array( $this, 'render_admin_page' )
			);
		}
	}

	/**
	 * Renders the 'Microsoft Entra ID' settings page.
	 */
	public function render_admin_page() {
		require_once( 'view/settings.php' );
	}

	/**
	 * Registers settings, sections and fields.
	 */
	public function register_settings() {

		// In Multisite/Network Admin we don't use the regular Settings API persistence (options.php),
		// because we store a single network-wide configuration using site options.
		if ( is_multisite() ) {
			add_settings_section(
				'aadsso_settings_general',
				__( 'General', 'aad-sso-wordpress' ),
				array( $this, 'settings_general_info' ),
				'aadsso_settings_page'
			);

			add_settings_section(
				'aadsso_settings_advanced',
				__( 'Advanced', 'aad-sso-wordpress' ),
				array( $this, 'settings_advanced_info' ),
				'aadsso_settings_page'
			);

			add_settings_field(
				'org_display_name',
				__( 'Display name', 'aad-sso-wordpress' ),
				array( $this, 'org_display_name_callback' ),
				'aadsso_settings_page',
				'aadsso_settings_general'
			);

			add_settings_field(
				'org_domain_hint', // id
				__( 'Domain hint', 'aad-sso-wordpress' ), // title
				array( $this, 'org_domain_hint_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'client_id', // id
				__( 'Client ID', 'aad-sso-wordpress' ), // title
				array( $this, 'client_id_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'client_secret', // id
				__( 'Client secret', 'aad-sso-wordpress' ), // title
				array( $this, 'client_secret_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'redirect_uri', // id
				__( 'Redirect URL', 'aad-sso-wordpress' ), // title
				array( $this, 'redirect_uri_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'logout_redirect_uri', // id
				__( 'Logout redirect URL', 'aad-sso-wordpress' ), // title
				array( $this, 'logout_redirect_uri_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'enable_full_logout', // id
				__( 'Enable full logout', 'aad-sso-wordpress' ), // title
				array( $this, 'enable_full_logout_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'field_to_match_to_upn', // id
				__( 'Field to match to UPN', 'aad-sso-wordpress' ), // title
				array( $this, 'field_to_match_to_upn_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'match_on_upn_alias', // id
				__( 'Match on alias of the UPN', 'aad-sso-wordpress' ), // title
				array( $this, 'match_on_upn_alias_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'enable_auto_provisioning', // id
				__( 'Enable auto-provisioning', 'aad-sso-wordpress' ), // title
				array( $this, 'enable_auto_provisioning_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'enable_auto_forward_to_aad', // id
				__( 'Enable auto-forward to Microsoft Entra ID', 'aad-sso-wordpress' ), // title
				array( $this, 'enable_auto_forward_to_aad_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'enable_aad_group_to_wp_role', // id
				__( 'Enable Microsoft Entra ID group to WordPress role association', 'aad-sso-wordpress' ), // title
				array( $this, 'enable_aad_group_to_wp_role_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'default_wp_role', // id
				__( 'Default WordPress role if not in Microsoft Entra ID group', 'aad-sso-wordpress' ), // title
				array( $this, 'default_wp_role_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'role_map', // id
				__( 'WordPress role to Microsoft Entra ID group map', 'aad-sso-wordpress' ), // title
				array( $this, 'role_map_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_general' // section
			);

			add_settings_field(
				'openid_configuration_endpoint', // id
				__( 'OpenID Connect configuration endpoint', 'aad-sso-wordpress' ), // title
				array( $this, 'openid_configuration_endpoint_callback' ), // callback
				'aadsso_settings_page', // page
				'aadsso_settings_advanced' // section
			);

			return;
		}

		// Single-site settings: use the core Settings API.
		register_setting(
			'aadsso_settings', // option_group
			'aadsso_settings', // option_name
			array( $this, 'sanitize_settings' ) // sanitize_callback
		);

		add_settings_section(
			'aadsso_settings_general',
			__( 'General', 'aad-sso-wordpress' ),
			array( $this, 'settings_general_info' ),
			'aadsso_settings_page'
		);

		add_settings_section(
			'aadsso_settings_advanced',
			__( 'Advanced', 'aad-sso-wordpress' ),
			array( $this, 'settings_advanced_info' ),
			'aadsso_settings_page'
		);

		add_settings_field(
			'org_display_name',
			__( 'Display name', 'aad-sso-wordpress' ),
			array( $this, 'org_display_name_callback' ),
			'aadsso_settings_page',
			'aadsso_settings_general'
		);

		add_settings_field(
			'org_domain_hint', // id
			__( 'Domain hint', 'aad-sso-wordpress' ), // title
			array( $this, 'org_domain_hint_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'client_id', // id
			__( 'Client ID', 'aad-sso-wordpress' ), // title
			array( $this, 'client_id_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'client_secret', // id
			__( 'Client secret', 'aad-sso-wordpress' ), // title
			array( $this, 'client_secret_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'redirect_uri', // id
			__( 'Redirect URL', 'aad-sso-wordpress' ), // title
			array( $this, 'redirect_uri_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'logout_redirect_uri', // id
			__( 'Logout redirect URL', 'aad-sso-wordpress' ), // title
			array( $this, 'logout_redirect_uri_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'enable_full_logout', // id
			__( 'Enable full logout', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_full_logout_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'field_to_match_to_upn', // id
			__( 'Field to match to UPN', 'aad-sso-wordpress' ), // title
			array( $this, 'field_to_match_to_upn_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'match_on_upn_alias', // id
			__( 'Match on alias of the UPN', 'aad-sso-wordpress' ), // title
			array( $this, 'match_on_upn_alias_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'enable_auto_provisioning', // id
			__( 'Enable auto-provisioning', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_auto_provisioning_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'enable_auto_forward_to_aad', // id
			__( 'Enable auto-forward to Microsoft Entra ID', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_auto_forward_to_aad_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'enable_aad_group_to_wp_role', // id
			__( 'Enable Microsoft Entra ID group to WordPress role association', 'aad-sso-wordpress' ), // title
			array( $this, 'enable_aad_group_to_wp_role_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'default_wp_role', // id
			__( 'Default WordPress role if not in Microsoft Entra ID group', 'aad-sso-wordpress' ), // title
			array( $this, 'default_wp_role_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'role_map', // id
			__( 'WordPress role to Microsoft Entra ID group map', 'aad-sso-wordpress' ), // title
			array( $this, 'role_map_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_general' // section
		);

		add_settings_field(
			'openid_configuration_endpoint', // id
			__( 'OpenID Connect configuration endpoint', 'aad-sso-wordpress' ), // title
			array( $this, 'openid_configuration_endpoint_callback' ), // callback
			'aadsso_settings_page', // page
			'aadsso_settings_advanced' // section
		);
	}

	/**
	 * Gets the array of roles determined by other plugins to be "editable".
	 */
	function get_editable_roles() {

		global $wp_roles;

		$all_roles = $wp_roles->roles;
		$editable_roles = apply_filters( 'editable_roles', $all_roles );

		return $editable_roles;
	}

	/**
	 * Cleans and validates form information before saving.
	 *
	 * @param array $input key-value information to be cleaned before saving.
	 *
	 * @return array The sanitized and valid data to be stored.
	 */
	public function sanitize_settings( $input ) {

		$sanitary_values = array();

		$text_fields = array(
			'org_display_name',
			'org_domain_hint',
			'client_id',
			'client_secret',
			'redirect_uri',
			'logout_redirect_uri',
			'openid_configuration_endpoint',
		);

		foreach ($text_fields as $text_field) {
			if ( isset( $input[ $text_field ] ) ) {
				$sanitary_values[ $text_field ] = sanitize_text_field( $input[ $text_field ] );
			}
		}

		// Default field_to_match_to_upn is 'email'
		$sanitary_values['field_to_match_to_upn'] = 'email';
		if ( isset( $input['field_to_match_to_upn'] )
		      && in_array( $input['field_to_match_to_upn'], array( 'email', 'login' ) )
		) {
			$sanitary_values['field_to_match_to_upn'] = $input['field_to_match_to_upn'];
		}

		// Default role for user that is not member of any Microsoft Entra ID group is null, which denies access.
		$sanitary_values['default_wp_role'] = null;
		if ( isset( $input['default_wp_role'] ) ) {
			$sanitary_values['default_wp_role'] = sanitize_text_field( $input['default_wp_role'] );
		}

		// Booleans: when key == value, this is considered true, otherwise false.
		$boolean_settings = array(
			'enable_auto_provisioning',
			'enable_auto_forward_to_aad',
			'enable_aad_group_to_wp_role',
			'match_on_upn_alias',
			'enable_full_logout',
		);
		foreach ( $boolean_settings as $boolean_setting )
		{
			if( isset( $input[ $boolean_setting ] ) ) {
				$sanitary_values[ $boolean_setting ] = ( $boolean_setting == $input[ $boolean_setting ] );
			} else {
				$sanitary_values[ $boolean_setting ] = false;
			}
		}

		/*
		 * Many of the roles in WordPress will not have Microsoft Entra ID groups associated with them.
		 * Go over all roles, removing the mapping for empty ones.
		 */
		if ( isset( $input['role_map'] ) ) {
			foreach( $input['role_map'] as $role_slug => $group_object_id ) {
				if( empty( $group_object_id ) ) {
					unset( $input['role_map'][ $role_slug ] );
				}
			}
			$sanitary_values['role_map'] = $input['role_map'];
		}

		// If the OpenID Connect configuration endpoint is changed, clear the cached values.
		$stored_oidc_config_endpoint = isset( $this->settings['openid_configuration_endpoint'] )
			? $this->settings['openid_configuration_endpoint'] : null;
		$new_oidc_config_endpoint = isset( $sanitary_values['openid_configuration_endpoint'] )
			? $sanitary_values['openid_configuration_endpoint'] : null;
		if ( $stored_oidc_config_endpoint !== $new_oidc_config_endpoint ) {
			delete_transient( 'aadsso_openid_configuration' );
			AADSSO::debug_log('Setting \'openid_configuration_endpoint\' changed, cleared cached OpenID Connect values.');
		}

		return $sanitary_values;
	}

	/**
	 * Renders details for the General settings section.
	 */
	public function settings_general_info() { }

	/**
	 * Renders details for the Advanced settings section.
	 */
	public function settings_advanced_info() { }

	/**
	 * Renders the `role_map` picker control.
	 */
	function role_map_callback() {
		printf( '<p>%s</p>',
			__( 'Map WordPress roles to Microsoft Entra ID groups.', 'aad-sso-wordpress' )
		);
		echo '<table>';
		printf(
			'<thead><tr><th>%s</th><th>%s</th></tr></thead>',
			__( 'WordPress Role', 'aad-sso-wordpress' ),
			__( 'Microsoft Entra ID Group Object ID', 'aad-sso-wordpress' )
		);
		echo '<tbody>';
		foreach( $this->get_editable_roles( ) as $role_slug => $role ) {
			echo '<tr>';
				echo '<td>' . htmlentities( $role['name'] ) . '</td>';
				echo '<td>';
					printf(
						'<input type="text" class="regular-text" name="aadsso_settings[role_map][%1$s]" '
						 . 'id="role_map_%1$s" value="%2$s" />',
						$role_slug,
						isset( $this->settings['role_map'][ $role_slug ] )
							? esc_attr( $this->settings['role_map'][ $role_slug ] )
							: ''
					);
				echo '</td>';
			echo '</tr>';
		}
		echo '</tbody>';
		echo '</table>';
	}

	/**
	 * Renders the `org_display_name` form control.
	 */
	public function org_display_name_callback()  {
		$this->render_text_field( 'org_display_name' );
		printf(
			'<p class="description">%s</p>',
			__( 'Display Name will be shown on the WordPress login screen.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `org_domain_hint` form control.
	 */
	public function org_domain_hint_callback()  {
		$this->render_text_field( 'org_domain_hint' );
		printf(
			'<p class="description">%s</p>',
			__( 'Provides a hint to Microsoft Entra ID about the domain or tenant they will be logging in to. If '
			     . 'the domain is federated, the user will be automatically redirected to federation '
			     . 'endpoint.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `client_id` form control
	 */
	public function client_id_callback() {
		$this->render_text_field( 'client_id' );
		printf(
			'<p class="description">%s</p>',
			__( 'The client ID of the Microsoft Entra ID application representing this blog.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `client_secret` form control
	 **/
	public function client_secret_callback() {
		$this->render_text_field( 'client_secret' );
		printf(
			'<p class="description">%s</p>',
			__( 'A secret key for the Microsoft Entra ID application representing this blog.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `redirect_uri` form control
	 **/
	public function redirect_uri_callback() {
		$this->render_text_field( 'redirect_uri' );
		printf(
			' <a href="#" onclick="jQuery(\'#redirect_uri\').val(\'%s\'); return false;">%s</a>'
			. '<p class="description">%s</p>',
			wp_login_url(),
			__( 'Set default', 'aad-sso-wordpress' ),
			__( 'The URL where the user is redirected to after authenticating with Microsoft Entra ID. '
			  . 'This URL must be registered in Microsoft Entra ID as a valid redirect URL, and it must be a '
			  . 'page that invokes the "authenticate" filter. If you don\'t know what to set, leave '
			  . 'the default value (which is this blog\'s login page).', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `logout_redirect_uri` form control
	 **/
	public function logout_redirect_uri_callback() {
		$this->render_text_field( 'logout_redirect_uri' );
		printf(
			' <a href="#" onclick="jQuery(\'#logout_redirect_uri\').val(\'%s\'); return false;">%s</a>'
			. '<p class="description">%s</p>',
			wp_login_url(),
			__( 'Set default', 'aad-sso-wordpress'),
			__( 'The URL where the user is redirected to after signing out of Microsoft Entra ID. '
			  . 'This URL must be registered in Microsoft Entra ID as a valid redirect URL. (This does not affect '
			  . ' logging out of the blog, it is only used when logging out of Microsoft Entra ID.)', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `field_to_match_to_upn` form control.
	 */
	public function field_to_match_to_upn_callback() {
		$selected =
		 isset( $this->settings['field_to_match_to_upn'] )
			? $this->settings['field_to_match_to_upn']
			: '';
		?>
		<select name="aadsso_settings[field_to_match_to_upn]" id="field_to_match_to_upn">
			<option value="email"<?php echo $selected == 'email' ? ' selected="selected"' : ''; ?>>
				<?php echo __( 'Email Address', 'aad-sso-wordpress' ); ?>
			</option>
			<option value="login"<?php echo $selected == 'login' ? ' selected="selected"' : ''; ?>>
				<?php echo __( 'Login Name', 'aad-sso-wordpress' ); ?>
			</option>
		</select>
		<?php
		printf(
			'<p class="description">%s</p>',
			__( 'This specifies the WordPress user field which will be used to match to the Microsoft Entra ID user\'s '
			  . 'UserPrincipalName.', 'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `match_on_upn_alias` checkbox control.
	 */
	public function match_on_upn_alias_callback() {
		$this->render_checkbox_field(
			'match_on_upn_alias',
			__( 'Match WordPress users based on the alias of their Microsoft Entra ID UserPrincipalName. For example, '
			  . 'Microsoft Entra ID username <code>bob@example.com</code> will match WordPress user <code>bob</code>.',
			    'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `default_wp_role` control.
	 */
	public function default_wp_role_callback() {

		// Default configuration should be most-benign
		if( ! isset( $this->settings['default_wp_role'] ) ) {
			$this->settings['default_wp_role'] = '';
		}

		echo '<select name="aadsso_settings[default_wp_role]" id="default_wp_role">';
		printf( '<option value="%s">%s</option>', '', '(None, deny access)' );
		foreach( $this->get_editable_roles() as $role_slug => $role ) {
			$selected = $this->settings['default_wp_role'] === $role_slug ? ' selected="selected"' : '';
			printf(
				'<option value="%s"%s>%s</option>',
				esc_attr( $role_slug ), $selected, htmlentities( $role['name'] )
			);
		}
		echo '</select>';
		printf(
			'<p class="description">%s</p>',
			__('This is the default role that users will be assigned to if matching Microsoft Entra ID group to '
			 . 'WordPress roles is enabled, but the signed in user isn\'t a member of any of the '
			 . 'configured Microsoft Entra ID groups.', 'aad-sso-wordpress')
		);
	}

	/**
	 * Renders the `enable_auto_provisioning` checkbox control.
	 */
	public function enable_auto_provisioning_callback() {
		$this->render_checkbox_field(
			'enable_auto_provisioning',
			__( 'Automatically create WordPress users, if needed, for authenticated Microsoft Entra ID users.',
				'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `enable_auto_forward_to_aad` checkbox control.
	 */
	public function enable_auto_forward_to_aad_callback() {
		$this->render_checkbox_field(
			'enable_auto_forward_to_aad',
			__( 'Automatically forward users to the Microsoft Entra ID to sign in, skipping the WordPress login screen.',
				'aad-sso-wordpress')
		);
	}

	/**
	 * Renders the `enable_aad_group_to_wp_role` checkbox control.
	 */
	public function enable_aad_group_to_wp_role_callback() {
		$this->render_checkbox_field(
			'enable_aad_group_to_wp_role',
			__( 'Automatically assign WordPress user roles based on Microsoft Entra ID group membership.',
				'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `openid_configuration_endpoint` form control
	 **/
	public function openid_configuration_endpoint_callback() {
		$this->render_text_field( 'openid_configuration_endpoint' );
		printf(
			' <a href="#" onclick="jQuery(\'#openid_configuration_endpoint\').val(\'%s\'); return false;">%s</a>'
			. '<p class="description">%s</p>',
			AADSSO_Settings::get_defaults( 'openid_configuration_endpoint' ),
			__( 'Set default', 'aad-sso-wordpress'),
			__( 'The OpenID Connect configuration endpoint to use. To support Microsoft Accounts and external '
			  . 'users (users invited in from other Microsoft Entra ID directories, known sometimes as "B2B users") you '
			  . 'must use: <code>https://login.microsoftonline.com/{tenant-id}/.well-known/openid-configuration</code>, '
			  . 'where <code>{tenant-id}</code> is the tenant ID or a verified domain name of your directory.',
				'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders the `enable_full_logout` checkbox control.
	 */
	public function enable_full_logout_callback() {
		$this->render_checkbox_field(
			'enable_full_logout',
			__( 'Do a full logout of Microsoft Entra ID when logging out of WordPress.',
				'aad-sso-wordpress' )
		);
	}

	/**
	 * Renders a simple text field and populates it with the setting value.
	 *
	 * @param string $name The setting name for the text input field.
	 */
	public function render_text_field( $name ) {
		$value = isset( $this->settings[ $name ] ) ? esc_attr( $this->settings[ $name ] ) : '';
		printf(
			'<input class="regular-text" type="text" '
			 . 'name="aadsso_settings[%1$s]" id="%1$s" value="%2$s" />',
			$name, $value
		);
		if ( in_array( $name, $this->settings_from_env, true ) ) {
			$env_map = array(
				'client_id'     => 'AADSSO_CLIENT_ID',
				'client_secret' => 'AADSSO_CLIENT_SECRET',
				'redirect_uri'  => 'AADSSO_REDIRECT_URI',
			);
			if ( isset( $env_map[ $name ] ) ) {
				printf(
					'<p class="description" style="color:#b45309;">&#x26A0; %s <code>%s</code></p>',
					esc_html__( 'This value is provided by the environment variable', 'aad-sso-wordpress' ),
					esc_html( $env_map[ $name ] )
				);
			}
		}
	}

	/**
	 * Renders a simple checkbox field and populates it with the setting value.
	 *
	 * @param string $name The setting name for the checkbox input field.
	 * @param string $label The label to use for the checkbox.
	 */
	public function render_checkbox_field( $name, $label ) {
		printf(
			'<input type="checkbox" name="aadsso_settings[%1$s]" id="%1$s" value="%1$s"%2$s />'
			 . '<label for="%1$s">%3$s</label>',
			$name,
			isset( $this->settings[ $name ] ) && $this->settings[ $name ] ? 'checked' : '',
			$label
		);
	}

	/**
	 * Indicates if user is currently on this settings page.
	 */
	public function is_on_options_page() {
		$screen = get_current_screen();
		return $screen->id === $this->options_page_id;
	}

	/**
	 * Ensures jQuery is loaded
	 */
	public function maybe_include_jquery() {
		if ( $this->is_on_options_page() ) {
			wp_enqueue_script( 'jquery' );
		}
	}

	/**
	 * Saves settings in Network Admin (Multisite).
	 */
	public function handle_network_settings_save() {
		if ( ! is_multisite() ) {
			wp_die( 'Not allowed.' );
		}

		if ( ! current_user_can( 'manage_network_options' ) ) {
			wp_die( 'Permission denied.' );
		}

		check_admin_referer( 'aadsso_network_settings_save', 'aadsso_network_settings_nonce' );

		$raw = isset( $_POST['aadsso_settings'] ) && is_array( $_POST['aadsso_settings'] )
			? wp_unslash( $_POST['aadsso_settings'] )
			: array();

		// Bail out with an error if we received no form data.
		if ( empty( $raw ) ) {
			wp_die(
				'<p><strong>Microsoft Entra ID SSO:</strong> No settings data received (empty POST). '
				. 'Please try again or check your server\'s <code>post_max_size</code> and <code>max_input_vars</code> settings.</p>'
				. '<a href="' . esc_url( network_admin_url( 'settings.php?page=aadsso_settings' ) ) . '">&larr; Back</a>'
			);
		}

		$sanitized = $this->sanitize_settings( $raw );

		// Write directly to wp_sitemeta, bypassing WordPress's option cache layer
		// (which was causing duplicate rows via repeated INSERTs due to stale Redis cache).
		global $wpdb;
		$network_id = get_current_network_id();

		// Delete ALL existing rows for this key (cleans up any duplicates).
		$wpdb->delete(
			$wpdb->sitemeta,
			array( 'site_id' => $network_id, 'meta_key' => 'aadsso_settings' )
		);

		// Insert the fresh value.
		$db_result = $wpdb->insert(
			$wpdb->sitemeta,
			array(
				'site_id'    => $network_id,
				'meta_key'   => 'aadsso_settings',
				'meta_value' => maybe_serialize( $sanitized ),
			)
		);

		// Also flush the object cache so subsequent get_site_option() calls in the
		// same or next request return the new value instead of a cached false.
		wp_cache_delete( $network_id . ':aadsso_settings', 'site-options' );
		wp_cache_delete( $network_id . ':notoptions',      'site-options' );

		if ( false === $db_result ) {
			wp_die(
				'<p><strong>Microsoft Entra ID SSO:</strong> Database write failed. '
				. 'Error: <code>' . esc_html( $wpdb->last_error ) . '</code></p>'
				. '<a href="' . esc_url( network_admin_url( 'settings.php?page=aadsso_settings' ) ) . '">&larr; Back</a>'
			);
		}

		wp_redirect( network_admin_url( 'settings.php?page=aadsso_settings&updated=true' ) );
		exit;
	}
}
